DiffractionPlan.scanParameters
DiamondLightSource/ispyb-database pull request #110
Opened 2022-06-28 12:01 UTC by stufisher

As discussed adds `scanParameters` to `DiffractionPlan` which mirrors the column in `DataCollection`. The idea is to store parameters that cannot be described by existing columns or may change with some frequency (a json blob to represent a series of params).

I think Jake uses the `DataCollection` counter-part to store beamline parameters not described by `DataCollection`

2022-06-28 13:06 UTC, stufisher commented
cc @jacobfilik

2022-08-11 07:29 UTC, KarlLevik requested changes
Could do with a column comment (even though we forgot to add a comment on the corresponding column in DCG ...).

2022-08-16 13:07 UTC, KarlLevik approved these changes
We discussed separately whether this was a duplication of the `ScanParametersService` + `ScanParametersModel` tables, but the conclusion is that those are different. The `array` text column in SPM is only intended for lists of parameter values. This PR is also consistent with the corresponding `scanParameters` column in the `DataCollectionGroup` table.

2022-08-22 11:53 UTC, KarlLevik approved these changes

2022-08-22 11:53 UTC, merged