Add offsets for blsampleimage
DiamondLightSource/ispyb-database pull request #48
Opened 2020-11-22 16:27 UTC by stufisher

2020-11-26 11:22 UTC, KarlLevik requested changes
I don't think the default values should be in quotes? Also please capitalise x and y in the column names :)

2020-11-26 11:33 UTC, stufisher commented
done

2020-11-26 11:37 UTC, KarlLevik approved these changes
Approved, assuming Travis is happy.

2021-02-08 08:39 UTC, KarlLevik approved these changes

2021-02-08 08:39 UTC, merged