Add type to blsubsample
DiamondLightSource/ispyb-database pull request #49
Opened 2020-11-22 16:29 UTC by stufisher

2020-11-26 11:33 UTC, KarlLevik requested changes
We had agreed on varchar(10)!!!

2020-11-26 11:35 UTC, stufisher commented
Sorry copied from my db update script rather than the jira ticket, fixed...

2020-11-26 11:41 UTC, KarlLevik requested changes
Sorry, could you also rename the file to use dashes between the date fields as that is the "standard" we have adopted from the collaboration repo, and also please make it say "BLSubSample" rather than "blsample"?

2020-12-10 16:20 UTC, KarlLevik approved these changes

2021-02-08 08:32 UTC, KarlLevik approved these changes

2021-02-08 08:32 UTC, merged