SPs for inserting/retrieving GridInfo entries via dcid
DiamondLightSource/ispyb-database pull request #65
Opened 2021-02-15 10:26 UTC by rjgildea

Add `upsert_dc_grid` and ``retrieve_grid_info_for_dc` stored procedures for inserting/retrieving `GridInfo` entries via a `dataCollectionId` rather than `dataCollectionGroupId`.

2021-02-15 11:19 UTC, KarlLevik requested changes
I think that looks good, but could you please add separate files for the individual stored procedures under `schemas/ispyb/stored_programs/`? Also, I don't see any grants for the `retrieve_grid_info_for_dc` stored procedure?

2021-02-22 10:25 UTC, KarlLevik commented on schemas/ispyb/stored_programs/sp_retrieve_grid_info_for_dc.sql
> +CREATE PROCEDURE `retrieve_grid_info_for_dcg`(IN p_dcgId int unsigned)
Looks like the wrong procedure, but you seem to have the right one in `routines.sql`.

2021-02-22 10:28 UTC, KarlLevik requested changes
Looks very good, except for the wrong sproc in the "retrieve" sproc file as per comment below.

2021-02-22 12:12 UTC, rjgildea commented
> Looks very good, except for the wrong sproc in the "retrieve" sproc file as per comment below.

Good spot - I think the correct one should be in there now!

2021-02-22 12:25 UTC, KarlLevik approved these changes

2021-02-22 12:27 UTC, merged